language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  # Install Python dependencies
  - pip install -e .[dev]

  # Install node dependencies, always using latest node
  - nvm install node
  - npm install
before_script:
  # Run the pre-commit hooks (linting etc)
  - pre-commit run --all-files
script:
  - megaqc test
  - npx webpack --mode production
