language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  # Install Python dependencies
  - pip install -e .[dev]

  # Install node dependencies, always using latest node
  - nvm install --lts
  - npm install
before_script:
  # Get the linting outputs, but don't fail if they're poor
  - megaqc lint || true
script:
  - megaqc test
  - npm run build
