matrix:
  include:
    -
      language: python
      python:
        - 3.5
        - 3.6
        - 3.7
      install:
        - pip install -e .
      before_script:
        # Get the linting outputs, but don't fail if they're poor
        - megaqc lint || true
      script: megaqc test
    -
      language: node
      python:
        - node
        - lts/*
      install:
        - npm install
      script: webpack --mode production
